server:
  port: 80

spring:
  application:
    name: ares-order-service
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: 192.168.0.200
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}

    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default: # 全局
            connect-timeout: 10000
            read-timeout: 10000
          ares-payment-service: # 指定服务
            connect-timeout: 2000
            read-timeout: 2000
      compression:
        request:
          enabled: true
          min-request-size: 2048 # 最小触发压缩的大小
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true

# feign日志以什么级别监控哪个接口
logging:
  level:
    jp:
      tokyo:
        leon:
          api:
            feign:
              PaymentClient: debug




