server:
  port: 80

spring:
  application:
    name: ares-order-service
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: 192.168.0.200
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}

    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default: # 全局
            connect-timeout: 10000
            read-timeout: 10000
          ares-payment-service: # 指定服务
            connect-timeout: 4000
            read-timeout: 4000



